PST-1812 use new php-component
keboola/ex-telemetry-data pull request #28
Opened 2024-06-25 18:37 UTC by zajca

2024-06-26 08:13 UTC, ondrajodas commented
nechám to @AdamVyborny odjebu se z review

2024-07-01 11:09 UTC, AdamVyborny requested changes
Jinak to vypadá správně :)

2024-07-01 11:09 UTC, AdamVyborny commented on src/Extractor.php
> +            '',
zase `null`

2024-07-01 11:09 UTC, AdamVyborny commented on composer.lock
> +            "version": "10.1.0",
Tady ještě updatovat radši

2024-07-01 11:09 UTC, AdamVyborny commented on tests/functional/activitycenter_mode_correct_telemetry_data_nntf/expected-code
> +0
zase rename `native-types-manifest` :-/

2024-07-01 14:27 UTC, AdamVyborny approved these changes
Super tím updatem se odjebaly ty duplicitní metadata 👍

2024-07-01 19:11 UTC, merged